name: range_map
description: A mapping from disjoint nonempty ranges to values.
version: 0.1.0
author: Fluidic Team <dev@fluidic.io>
homepage: https://github.com/kseo/range_map

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  quiver_hashcode: any
  quiver_iterables: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
