name: range_map
description: A mapping from disjoint nonempty ranges to values.
version: 0.2.0
author: Fluidic Team <dev@fluidic.io>
homepage: https://github.com/fluidic/range_map

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  quiver_hashcode: '>=1.0.0 <2.0.0'
  quiver_iterables: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
